### ISSUE TITLE
Need Some Demo 

### ISSUE THREAD

**Issue by 59-lmq** [caiyilian/file_split#1]
Dear Author, 
No doubt that it's a great projection. However, could u please add more demo to illustrate how to use your projection?
As I don't know what the big_file means. A zip file or any file that its parameter is bigger than 1GB?
Thanks your great job again! Hoping for your response!

**Comment by caiyilian** [comment]
Oh, dear `Mingqian`, I sincerely apologize for my oversight. 'big_file' refers to **the file you want to split**. Generally, when you want to divide a file into smaller pieces, it's because you **consider** that file to be large. For example, you might want to **transfer this file**, but if it's too big, the transfer time can increase significantly. If the connection **drops midway**, you would need to **retransmit** the entire file. Therefore, you might want to split it into smaller files. **However**, the 'big_file' to be split **doesn't necessarily** have to be large; it can be **any file**, regardless of size. 
Thank you for pointing out this omission in my project. 
Wishing you good health and longevity!

**Comment by caiyilian** [comment]
Oh, dear `Mingqian`, I sincerely apologize for my oversight. 'big_file' refers to **the file you want to split**. Generally, when you want to divide a file into smaller pieces, it's because you **consider** that file to be large. For example, you might want to **transfer this file**, but if it's too big, the transfer time can increase significantly. If the connection **drops midway**, you would need to **retransmit** the entire file. Therefore, you might want to split it into smaller files. **However**, the 'big_file' to be split **doesn't necessarily** have to be large; it can be **any file**, regardless of size. 
Thank you for pointing out this omission in my project. 
Wishing you good health and longevity! @59-lmq @59-lmq

**Comment by 59-lmq** [comment]
OKK, Thanks for Your Reponse! I'll try it later!😘

**Comment by caiyilian** [comment]
Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? Why not star? 🤯@59-lmq

**Comment by 59-lmq** [comment]
Already Star！😂
